### ISSUE TITLE
[Feature request] Add support for Discord

### ISSUE THREAD

**Issue by maurelius** [ben-xo/sslscrobbler#26]
Would love to see this have support to post to Discord channels through a webhook or bot

**Comment by ben-xo** [comment]
Was considering adding this anyway! Should be easy, once I familiarise myself with a suitable Discord API client!

**Comment by VxJasonxV** [comment]
https://github.com/discord-php/DiscordPHP

**Comment by ben-xo** [comment]
> https://github.com/discord-php/DiscordPHP

yep - although that requires me to start using composer (very modern 😂) which is a bigger refactor than simply dropping a library into External.

I also found https://github.com/cubiclesoft/php-discord-sdk which is more lightweight and more in keeping with the rather... erm... "traditional" architecture of sslscrobbler.

**Comment by ben-xo** [comment]
Alright… now supported in v0.27 @maurelius

**Comment by maurelius** [comment]
Will pull and test it out. Thanks for implementing this!
