### ISSUE TITLE
Potential MacOS 15 issue - /usr/bin/php not found

### ISSUE THREAD

**Issue by dfraser** [ben-xo/sslscrobbler#27]
It looks like, on my Mac at least, Monterey has removed php from /usr/bin/php.

Homebrew installs it as /usr/local/bin/php -- not sure if platypus can look in two places.

This issue might be unique to my system.  

Running from the command line with the Homebrew-installed php works great.

**Comment by ben-xo** [comment]
Ooh thanks for pointing that out. I'll work on a fix or update the docs or whatever is appropriate.

**Comment by ben-xo** [comment]
Fixed in 0d093ce

**Comment by ben-xo** [comment]
Would you care to test it @dfraser ?
